[build.environment]
NODE_VERSION = "20"
AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[functions]
directory = "functions"
external_node_modules = ["@sparticuz/chromium"]

[[redirects]]
from = "/*"
to = "/.netlify/builders/screenshot"
status = 200
force = true
